import { Inter } from "next/font/google";

import 'bootstrap/dist/css/bootstrap.min.css';

import AuthProvider from "@/context/authProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>{children}</body>
      </AuthProvider>

    </html>
  );
}
