import { Inter } from "next/font/google";

import 'bootstrap/dist/css/bootstrap.min.css';
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/context/authProvider";
import Navbar from "@/component/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>

        <AuthProvider>
          <Navbar />
          {children}
          <Toaster />
        </AuthProvider>
      </body>


    </html>
  );
}
